CREATE TABLE persons (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY
                    CONSTRAINT person_pkey PRIMARY KEY,
    username    VARCHAR(255) NOT NULL,
    first_name  varchar(255) NOT NULL,
    last_name   varchar(255) NOT NULL,
    email       varchar(255) NOT NULL
);

CREATE TABLE person_role (
    person_id INTEGER NOT NULL
        CONSTRAINT fk_person_person_role
            REFERENCES persons ON UPDATE CASCADE ON DELETE CASCADE,
    role    VARCHAR(64) NOT NULL
);



